FROM node:22.3.0-alpine3.19 as build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --silent
COPY . .
# EXPOSE 3000
# CMD [ "npm", "run"]
RUN npm run build
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]