services:
  backend:
    image: backend
    build: 
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    container_name: backend
    restart: unless-stopped
    depends_on:
      - mongodb
  frontend:
    image: frontend
    build: 
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    container_name: frontend
    restart: unless-stopped
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./mongodb
        target: /data/db