# syntax = docker/dockerfile:1.5
FROM python:3.12-slim
ADD . .
RUN --mount=type=cache,target=/root/.cache pip install -r requirements.txt
ENV MONGODB_URI mongodb://user:pass@mongodb
# CMD ["python3 -m uvicorn main:app --reload --port 8000"]
# CMD ["fastapi", "run", "app/main.py", "--port", "8000"]
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--port=8000"]